/**
 * 1:1 TypeScript port of the backend's pure metric functions.
 *
 * Source of truth: confiddo/backend/app/services/metrics_service.py
 *   calculate_air                 :87-106
 *   calculate_tfa                 :109-141
 *   calculate_ocb                 :144-174
 *   calculate_hup                 :177-209
 *   calculate_phe                 :212-236
 *   calculate_scc                 :239-272
 *   calculate_dpi                 :275-316
 *   calculate_rgd                 :319-384
 *   calculate_fad                 :387-458
 *   calculate_tcr                 :461-501
 *   calculate_hsb                 :504-557
 *   calculate_peb                 :560-604
 *   calculate_ewp                 :607-647
 *   calculate_dap                 :650-686
 *   calculate_gep                 :689-727
 *   DIFFICULTY_WEIGHTS / calculate_weighted_accuracy :730-757
 *   _DIFF_TO_THETA / calculate_student_theta         :765-791
 *   calculate_all_metrics_pure    :798-826
 *
 * DISPLAY/VERIFICATION ONLY — the backend stays authoritative.
 * Verified against the Python source 2026-06-11 (golden values generated by
 * executing the actual Python functions).
 */

import type { AllMetrics, AttemptData, MetricResult, SessionData } from "./types";

// ──────────────────────────────────────────────────────────────────────
// Python rounding semantics
// ──────────────────────────────────────────────────────────────────────

/**
 * Python's built-in round(): correctly rounds the TRUE binary value of the
 * double, with round-half-to-EVEN only on EXACT ties (CPython uses David
 * Gay's correctly-rounded dtoa — see Python/pystrtod.c).
 *
 * Two JS pitfalls this implementation avoids:
 *  - Math.round rounds .5 halves up (Math.round(4.5)=5, Python round(4.5)=4).
 *  - A naive multiply-then-round can land on a floating-point .5 that is NOT
 *    a true tie: 0.12345*1e4 === 1234.5 exactly, yet the double 0.12345 is
 *    slightly ABOVE the tie, so Python gives round(0.12345, 4) = 0.1235 while
 *    banker's-rounding the product gives 0.1234. (A true tie at ndigits=4 is
 *    impossible for a double — (2k+1)/2e4 has 5^4 in the denominator — so on
 *    a .5 product the decision MUST come from the exact value.) Ties are
 *    therefore disambiguated exactly via BigInt rational comparison.
 * Used everywhere the Python code calls round(x) / round(x, n).
 */
export function pythonRound(value: number, ndigits = 0): number {
  if (!Number.isFinite(value)) return value;
  const m = 10 ** ndigits; // exact in binary for the ndigits used here (0..4)
  const scaled = value * m;
  const floor = Math.floor(scaled);
  const diff = scaled - floor;
  // floor+0.5 is itself representable at these magnitudes, so the correctly
  // rounded product can never cross the tie — diff <> 0.5 is decisive.
  if (diff > 0.5) return (floor + 1) / m;
  if (diff < 0.5) return floor / m;
  // Product landed exactly on .5 — compare the EXACT value of `value`
  // against the exact tie (2*floor+1)/(2*m).
  const cmp = compareExactToRational(value, 2 * floor + 1, 2 * m);
  if (cmp > 0) return (floor + 1) / m;
  if (cmp < 0) return floor / m;
  return (floor % 2 === 0 ? floor : floor + 1) / m; // true tie -> half-to-even
}

/**
 * Exact sign of (value - num/den) for a finite double and safe-integer
 * num / den (den > 0), via the IEEE-754 bit decomposition value = ±mant·2^exp.
 */
function compareExactToRational(value: number, num: number, den: number): number {
  const view = new DataView(new ArrayBuffer(8));
  view.setFloat64(0, value);
  const bits = view.getBigUint64(0);
  const sign = bits >> 63n ? -1n : 1n;
  const expBits = Number((bits >> 52n) & 0x7ffn);
  let mant = bits & 0xfffffffffffffn;
  let exp: number;
  if (expBits === 0) {
    exp = -1074; // subnormal
  } else {
    mant |= 0x10000000000000n;
    exp = expBits - 1075;
  }
  // value = sign·mant·2^exp;  value <=> num/den  ⟺  sign·mant·den·2^exp <=> num
  let lhs = sign * mant * BigInt(den);
  let rhs = BigInt(num);
  if (exp >= 0) lhs <<= BigInt(exp);
  else rhs <<= BigInt(-exp);
  return lhs < rhs ? -1 : lhs > rhs ? 1 : 0;
}

/**
 * Python dict.get(key, default). A bare `obj[key] ?? dflt` would resolve
 * Object.prototype members (e.g. difficulty === "constructor") instead of
 * falling back to the default like Python's dict.get does.
 */
const dictGet = (map: Record<string, number>, key: string, dflt: number): number =>
  Object.hasOwn(map, key) ? map[key] : dflt;

const round4 = (x: number): number => pythonRound(x, 4);

const answered = (attempts: AttemptData[]): AttemptData[] =>
  attempts.filter((a) => a.selectedOptionId !== null);

/** Python: sorted(attempts, key=lambda a: a.created_at or datetime.min) — stable sort. */
function sortByCreatedAt(attempts: AttemptData[]): AttemptData[] {
  return [...attempts].sort(
    (a, b) =>
      (a.createdAt ? a.createdAt.getTime() : Number.MIN_SAFE_INTEGER) -
      (b.createdAt ? b.createdAt.getTime() : Number.MIN_SAFE_INTEGER),
  );
}

// ──────────────────────────────────────────────────────────────────────
// m01 AIR — Attempt Initiation Rate (:87-106)
// ──────────────────────────────────────────────────────────────────────

export function calculateAir(attempts: AttemptData[], questionsShown: number): MetricResult {
  // gave_up_after_wrong COUNTS as attempted — AIR measures INITIATION.
  const attempted = attempts.filter(
    (a) => a.selectedOptionId !== null || a.gaveUpAfterWrong,
  ).length;
  const score = questionsShown > 0 ? attempted / questionsShown : 0;

  let status: MetricResult["status"];
  if (score >= 0.85) status = "green";
  else if (score >= 0.6) status = "yellow";
  else status = "red";

  return { score: round4(score), status };
}

// ──────────────────────────────────────────────────────────────────────
// m02 TFA — Time-to-First-Action (:109-141)
// ──────────────────────────────────────────────────────────────────────

export function calculateTfa(attempts: AttemptData[], accuracy?: number | null): MetricResult {
  const tfaValues = answered(attempts).map((a) => a.timeSpentMs);
  if (tfaValues.length === 0) return { score: 0, status: "red", category: "no_data" };

  let acc: number;
  if (accuracy === undefined || accuracy === null) {
    const total = answered(attempts).length;
    const correct = attempts.filter((a) => a.isCorrect).length;
    acc = total > 0 ? correct / total : 0;
  } else {
    acc = accuracy;
  }

  const avgTfa = tfaValues.reduce((s, t) => s + t, 0) / tfaValues.length;

  if (avgTfa < 3000) {
    if (acc >= 0.7) return { score: avgTfa, status: "green", category: "quick_knowledgeable" };
    if (acc >= 0.4) return { score: avgTfa, status: "yellow", category: "fast_mixed" };
    return { score: avgTfa, status: "red", category: "rushing" };
  }
  if (avgTfa <= 15000) return { score: avgTfa, status: "green", category: "deliberate" };
  if (avgTfa <= 60000) {
    if (acc >= 0.7) return { score: avgTfa, status: "green", category: "careful_accurate" };
    return { score: avgTfa, status: "yellow", category: "delayed" };
  }
  return { score: avgTfa, status: "red", category: "timeout" };
}

// ──────────────────────────────────────────────────────────────────────
// m03 OCB — Option Change Behavior (:144-174)
// ──────────────────────────────────────────────────────────────────────

export function calculateOcb(attempts: AttemptData[], accuracy: number): MetricResult {
  const attempted = answered(attempts);
  if (attempted.length === 0) return { score: 0, status: "red", category: "no_data" };

  const avgChanges = attempted.reduce((s, a) => s + a.optionChanges, 0) / attempted.length;

  if (avgChanges <= 0.5) {
    if (accuracy >= 0.7) return { score: avgChanges, status: "green", category: "decisive_correct" };
    if (accuracy >= 0.4) return { score: avgChanges, status: "yellow", category: "stable_mixed" };
    return { score: avgChanges, status: "red", category: "clicking_through" };
  }
  if (avgChanges <= 2.5) {
    if (accuracy >= 0.5) return { score: avgChanges, status: "green", category: "reflective" };
    return { score: avgChanges, status: "yellow", category: "uncertain" };
  }
  return { score: avgChanges, status: "red", category: "insecure" };
}

// ──────────────────────────────────────────────────────────────────────
// m04 HUP — Hint Utilization Pattern (:177-209)
// ──────────────────────────────────────────────────────────────────────

export function calculateHup(attempts: AttemptData[], accuracy?: number | null): MetricResult {
  const attempted = answered(attempts);
  if (attempted.length === 0) return { score: 0, status: "green", category: "no_data" };

  const hintsUsedCount = attempted.filter((a) => a.hintsUsed > 0).length;
  const hintRate = hintsUsedCount / attempted.length;

  let acc: number;
  if (accuracy === undefined || accuracy === null) {
    const correct = attempted.filter((a) => a.isCorrect).length;
    acc = correct / attempted.length;
  } else {
    acc = accuracy;
  }

  if (hintRate > 0.8) {
    const hinted = attempted.filter((a) => a.hintsUsed > 0);
    const hintedCorrect = hinted.filter((a) => a.isCorrect).length;
    const hintedAccuracy = hinted.length > 0 ? hintedCorrect / hinted.length : 0;
    if (hintedAccuracy < 0.3) {
      return { score: hintRate, status: "red", category: "dependent_not_learning" };
    }
    return { score: hintRate, status: "yellow", category: "dependent_but_learning" };
  }
  if (hintRate > 0.6) return { score: hintRate, status: "yellow", category: "dependent" };
  if (hintRate === 0 && acc < 0.4) {
    return { score: hintRate, status: "yellow", category: "should_seek_help" };
  }
  return { score: hintRate, status: "green", category: "healthy" };
}

// ──────────────────────────────────────────────────────────────────────
// m05 PHE — Post-Hint Engagement (:212-236)
// ──────────────────────────────────────────────────────────────────────

export function calculatePhe(attempts: AttemptData[], accuracy: number): MetricResult {
  const hinted = attempts.filter((a) => a.hintsUsed > 0);

  if (hinted.length === 0) {
    if (accuracy >= 0.4) return { score: 1.0, status: "green", category: "independent" };
    return { score: 0.5, status: "yellow", category: "should_seek_help" };
  }

  const continued = hinted.filter((a) => a.selectedOptionId !== null).length;
  const score = continued / hinted.length;

  if (score >= 0.8) return { score: round4(score), status: "green" };
  if (score >= 0.5) return { score: round4(score), status: "yellow" };
  return { score: round4(score), status: "red" };
}

// ──────────────────────────────────────────────────────────────────────
// m06 SCC — Session Completion Consistency (:239-272)
// ──────────────────────────────────────────────────────────────────────

export function calculateScc(
  session: SessionData,
  attempts: AttemptData[],
  accuracy: number,
): MetricResult {
  const completionRate = session.status === "completed" ? 1.0 : 0.0;

  // Focus penalty placeholder — hardcoded 0 in the backend (:248)
  const focusPenalty = 0.0;

  const numQuestions = attempts.length;
  const expectedMinMs = numQuestions * 30000; // 30s minimum per question
  const totalTime = session.totalTimeMs || 0;

  let rushingPenalty = 0.0;
  if (totalTime > 0) {
    if (totalTime < expectedMinMs * 0.3 && accuracy < 0.5) rushingPenalty = 0.5;
    else if (totalTime < expectedMinMs * 0.5 && accuracy < 0.5) rushingPenalty = 0.25;
    // accuracy >= 0.50 -> NO rushing penalty regardless of speed
  }

  const score = completionRate * (1 - focusPenalty * 0.5) * (1 - rushingPenalty);

  let status: MetricResult["status"];
  if (score >= 0.85 && focusPenalty < 0.2) status = "green";
  else if (score >= 0.6 && focusPenalty < 0.5) status = "yellow";
  else status = "red";

  return { score: round4(score), status };
}

// ──────────────────────────────────────────────────────────────────────
// m07 DPI — Difficulty Persistence Index (:275-316)
// ──────────────────────────────────────────────────────────────────────

export function calculateDpi(attempts: AttemptData[]): MetricResult {
  const wrongAttempts = attempts.filter((a) => a.persistedAfterWrong || a.gaveUpAfterWrong);

  // With 0-2 wrong answers, DPI has too few data points to judge persistence.
  // Returns neutral so the level algorithm treats it as green.
  if (wrongAttempts.length <= 2) {
    const completed = answered(attempts).length;
    const baseRate = attempts.length > 0 ? completed / attempts.length : 0;
    // NOTE: score is the RAW base rate (the Python neutral branch does not round).
    return { score: baseRate, status: "neutral", category: "insufficient_wrong_data" };
  }

  // NOT PORTED: metrics_service.py:290-298 (`if not wrong_attempts:` branch) is
  // unreachable dead code — the `<= 2 -> neutral` check above always returns
  // first when wrong_attempts is empty. Documented in ARCHITECTURE.md §9.6.

  const persisted = wrongAttempts.filter((a) => a.persistedAfterWrong).length;
  const gaveUpCount = wrongAttempts.filter((a) => a.gaveUpAfterWrong).length;

  // Phase 1 fallback: weight gave_up at 0.3
  const engagement = (persisted * 1.0 + gaveUpCount * 0.3) / wrongAttempts.length;

  const completed = answered(attempts).length;
  const baseRate = attempts.length > 0 ? completed / attempts.length : 0;

  const score = baseRate * 0.4 + engagement * 0.6;

  if (score >= 0.7 && engagement >= 0.6) {
    return { score: round4(score), status: "green", persistenceRate: round4(engagement) };
  }
  if (score >= 0.45 || engagement >= 0.4) {
    return { score: round4(score), status: "yellow", persistenceRate: round4(engagement) };
  }
  return { score: round4(score), status: "red", persistenceRate: round4(engagement) };
}

// ──────────────────────────────────────────────────────────────────────
// m08 RGD — Rapid Guessing Detection (:319-384)
// ──────────────────────────────────────────────────────────────────────

const RGD_STATIC_THRESHOLDS: Record<string, number> = { easy: 2000, medium: 3000, hard: 5000 };
const RGD_DEFAULT_THRESHOLD = 3000;
const RGD_NT15_FLOOR_MS = 1000;

export function calculateRgd(attempts: AttemptData[]): MetricResult {
  let fastCorrect = 0;
  let fastWrong = 0;
  let totalAttempted = 0;

  for (const a of attempts) {
    if (a.selectedOptionId === null) continue;
    totalAttempted += 1;

    // NT15 population-median threshold when available, else static fallback.
    // Python `int(...)` truncates toward zero -> Math.trunc.
    let threshold: number;
    if (a.populationMedianMs !== null && a.populationMedianMs > 0) {
      threshold = Math.max(Math.trunc(a.populationMedianMs * 0.15), RGD_NT15_FLOOR_MS);
    } else {
      threshold = dictGet(RGD_STATIC_THRESHOLDS, a.difficulty, RGD_DEFAULT_THRESHOLD);
    }

    if (a.timeSpentMs < threshold) {
      if (a.isCorrect) fastCorrect += 1; // Evidence of knowledge
      else fastWrong += 1; // Evidence of guessing
    }
  }

  if (totalAttempted === 0) return { score: 0, status: "red" };

  const totalFast = fastCorrect + fastWrong;

  if (totalFast === 0) return { score: 0.0, status: "green", category: "no_fast_answers" };
  if (totalFast < 3) return { score: 0.0, status: "green", category: "insufficient_fast_data" };

  const guessRatio = fastWrong / totalFast;
  const overallRate = fastWrong / totalAttempted;

  // The more lenient of the two — protects fast students with occasional typos
  const effectiveRate = Math.min(guessRatio, overallRate);

  const overallAccuracy =
    totalAttempted > 0 ? attempts.filter((a) => a.isCorrect).length / totalAttempted : 0;
  if (overallAccuracy >= 0.7 && effectiveRate <= 0.3) {
    return { score: round4(effectiveRate), status: "green", category: "fast_knowledgeable" };
  }

  if (effectiveRate < 0.25) return { score: round4(effectiveRate), status: "green" };
  if (effectiveRate <= 0.35) return { score: round4(effectiveRate), status: "yellow" };
  return { score: round4(effectiveRate), status: "red" };
}

// ──────────────────────────────────────────────────────────────────────
// m09 FAD — Fatigue/Attention Decay (:387-458)
// ──────────────────────────────────────────────────────────────────────

const FAD_DIFF_SCORE: Record<string, number> = { easy: 1, medium: 2, hard: 3, very_hard: 4 };

export function calculateFad(attempts: AttemptData[]): MetricResult {
  if (attempts.length < 6) {
    return { score: 0.0, status: "neutral", category: "insufficient_data" };
  }

  const mid = Math.floor(attempts.length / 2); // Python len//2
  const early = attempts.slice(0, mid);
  const late = attempts.slice(mid);

  const diffScore = (a: AttemptData): number => dictGet(FAD_DIFF_SCORE, a.difficulty, 2);
  const earlyDiff = early.reduce((s, a) => s + diffScore(a), 0) / Math.max(early.length, 1);
  const lateDiff = late.reduce((s, a) => s + diffScore(a), 0) / Math.max(late.length, 1);
  const difficultyIncreased = lateDiff > earlyDiff + 0.5;

  const greenThreshold = difficultyIncreased ? 0.2 : 0.1;
  const yellowThreshold = difficultyIncreased ? 0.4 : 0.25;

  const earlyEasy = early.filter((a) => a.difficulty === "easy");
  const lateEasy = late.filter((a) => a.difficulty === "easy");

  const accOf = (group: AttemptData[]): number =>
    group.length > 0 ? group.filter((a) => a.isCorrect).length / group.length : 0;

  if (earlyEasy.length === 0 || lateEasy.length === 0) {
    // All-question path: thresholds widened by +0.05
    const earlyAcc = accOf(early);
    const lateAcc = accOf(late);
    const drop = earlyAcc - lateAcc;

    if (drop < greenThreshold + 0.05) {
      const improvement = lateAcc - earlyAcc;
      if (improvement > 0.3) {
        return { score: round4(improvement), status: "yellow", category: "suspicious_improvement" };
      }
      return { score: round4(drop), status: "green" };
    }
    if (drop <= yellowThreshold + 0.05) return { score: round4(drop), status: "yellow" };
    return { score: round4(drop), status: "red" };
  }

  // Easy-only normalization path
  const earlyEasyAcc = accOf(earlyEasy);
  const lateEasyAcc = accOf(lateEasy);
  const drop = earlyEasyAcc - lateEasyAcc;

  if (drop < greenThreshold) {
    const improvement = lateEasyAcc - earlyEasyAcc;
    if (improvement > 0.3) {
      return { score: round4(improvement), status: "yellow", category: "suspicious_improvement" };
    }
    return { score: round4(drop), status: "green", category: "sustained" };
  }
  if (drop <= yellowThreshold) {
    return { score: round4(drop), status: "yellow", category: "mild_decline" };
  }

  // Red — categorize by speed ratio over ALL early/late attempts (not easy-only)
  const earlyTime =
    early.length > 0 ? early.reduce((s, a) => s + a.timeSpentMs, 0) / early.length : 1;
  const lateTime = late.length > 0 ? late.reduce((s, a) => s + a.timeSpentMs, 0) / late.length : 1;
  const speedRatio = earlyTime > 0 ? lateTime / earlyTime : 1.0;

  let cat: string;
  if (speedRatio < 0.7) cat = "disengagement";
  else if (speedRatio > 1.3) cat = "cognitive_fatigue";
  else cat = "decline";

  return { score: round4(drop), status: "red", category: cat };
}

// ──────────────────────────────────────────────────────────────────────
// m10 TCR — Test Completion Rhythm (:461-501)
// ──────────────────────────────────────────────────────────────────────

export function calculateTcr(attempts: AttemptData[]): MetricResult {
  if (attempts.length < 3) return { score: 0.0, status: "yellow" };

  const groups = new Map<string, number[]>();
  for (const a of attempts) {
    if (a.selectedOptionId === null) continue;
    const list = groups.get(a.difficulty);
    if (list) list.push(a.timeSpentMs);
    else groups.set(a.difficulty, [a.timeSpentMs]);
  }

  let maxCv = 0.0;
  for (const times of groups.values()) {
    if (times.length < 2) continue;
    const meanT = times.reduce((s, t) => s + t, 0) / times.length;
    if (meanT === 0) continue;
    const stdT = Math.sqrt(times.reduce((s, t) => s + (t - meanT) ** 2, 0) / times.length);
    const cv = stdT / meanT;
    maxCv = Math.max(maxCv, cv);
  }

  // Dump pattern: last 3 much faster than first 3
  const allTimes = answered(attempts).map((a) => a.timeSpentMs);
  let dump = false;
  if (allTimes.length >= 6) {
    const f3 = (allTimes[0] + allTimes[1] + allTimes[2]) / 3;
    const l3 = allTimes.slice(-3).reduce((s, t) => s + t, 0) / 3;
    if (f3 > 0 && l3 < f3 * 0.3) dump = true;
  }

  if (maxCv < 0.5 && !dump) return { score: round4(maxCv), status: "green" };
  if (maxCv <= 0.8 && !dump) return { score: round4(maxCv), status: "yellow" };
  return { score: round4(maxCv), status: "red", dumpDetected: dump };
}

// ──────────────────────────────────────────────────────────────────────
// m11 HSB — Help-Seeking Behavior Quality (:504-557)
// ──────────────────────────────────────────────────────────────────────

export function calculateHsb(attempts: AttemptData[], accuracy?: number | null): MetricResult {
  let acc: number;
  if (accuracy === undefined || accuracy === null) {
    const total = answered(attempts).length;
    const correct = attempts.filter((a) => a.isCorrect).length;
    acc = total > 0 ? correct / total : 0;
  } else {
    acc = accuracy;
  }

  let strategic = 0;
  let unnecessary = 0;
  let missed = 0;

  for (const a of attempts) {
    const difficulty = a.difficulty;

    if (a.hintsUsed > 0) {
      if ((difficulty === "medium" || difficulty === "hard") && !a.isCorrect) strategic += 1;
      else if (difficulty === "easy") unnecessary += 1;
    } else {
      if ((difficulty === "medium" || difficulty === "hard") && !a.isCorrect) {
        if (a.gaveUpAfterWrong) {
          // Chose solution = a form of help-seeking — not "missed"
        } else if (a.selectedOptionId === null) {
          missed += 1;
        } else if (!a.persistedAfterWrong && !a.gaveUpAfterWrong) {
          missed += 1;
        }
      }
    }
  }

  const denom = strategic + unnecessary + missed;
  if (denom === 0) {
    if (acc >= 0.8) return { score: 1.0, status: "green", category: "no_help_needed" };
    if (acc >= 0.5) return { score: 0.5, status: "yellow", category: "uncertain" };
    return { score: 0.0, status: "yellow", category: "should_have_sought_help" };
  }

  const score = strategic / denom;

  if (score >= 0.6) return { score: round4(score), status: "green", category: "strategic" };
  if (score >= 0.3) return { score: round4(score), status: "yellow", category: "mixed" };
  return { score: round4(score), status: "red", category: "unfocused" };
}

// ──────────────────────────────────────────────────────────────────────
// m12 PEB — Post-Error Behavior Pattern (:560-604)
// ──────────────────────────────────────────────────────────────────────

export function calculatePeb(attempts: AttemptData[]): MetricResult {
  const ordered = sortByCreatedAt(attempts);

  if (ordered.length < 2) return { score: 1.0, status: "yellow" };

  const times = answered(ordered).map((a) => a.timeSpentMs);
  if (times.length === 0) return { score: 0, status: "red" };
  const avgTime = times.reduce((s, t) => s + t, 0) / times.length;

  let resilient = 0;
  let postErrorCount = 0;

  for (let i = 0; i < ordered.length - 1; i++) {
    if (!ordered[i].isCorrect && ordered[i].selectedOptionId !== null) {
      postErrorCount += 1;
      const nextA = ordered[i + 1];

      if (nextA.selectedOptionId === null) {
        // Cascade skip — not resilient
      } else if (nextA.timeSpentMs < avgTime * 0.3) {
        // Rush after error — not resilient
      } else if (nextA.timeSpentMs > avgTime * 2.5) {
        if (nextA.difficulty === "medium" || nextA.difficulty === "hard") {
          resilient += 1; // Harder Q expected to take longer
        }
        // else: easy Q + very slow = freeze
      } else {
        resilient += 1;
      }
    }
  }

  if (postErrorCount === 0) return { score: 1.0, status: "green" };

  const rate = resilient / postErrorCount;

  if (rate >= 0.7) return { score: round4(rate), status: "green" };
  if (rate >= 0.4) return { score: round4(rate), status: "yellow" };
  return { score: round4(rate), status: "red" };
}

// ──────────────────────────────────────────────────────────────────────
// m13 EWP — Effort-Withdrawal Pattern (:607-647)
// ──────────────────────────────────────────────────────────────────────

export function calculateEwp(attempts: AttemptData[]): MetricResult {
  const ordered = sortByCreatedAt(attempts);
  const n = ordered.length;
  if (n < 6) return { score: 1.0, status: "yellow" };

  const third = Math.max(2, Math.floor(n / 3)); // Python max(2, n // 3)
  const early = ordered.slice(0, third);
  const late = ordered.slice(-third);

  const effort = (group: AttemptData[]): number =>
    group.reduce(
      (s, a) => s + a.timeSpentMs + a.optionChanges * 2000 + a.hintsUsed * 3000,
      0,
    ) / group.length;

  const earlyEffort = effort(early);
  const lateEffort = effort(late);

  if (earlyEffort === 0) return { score: 0, status: "red" };

  const ratio = lateEffort / earlyEffort;

  if (ratio > 0.7) return { score: round4(ratio), status: "green" };

  const earlyAcc = early.filter((a) => a.isCorrect).length / early.length;
  const lateAcc = late.filter((a) => a.isCorrect).length / late.length;

  if (lateAcc >= earlyAcc * 0.85) {
    return { score: round4(ratio), status: "green", category: "efficient" };
  }
  if (ratio >= 0.4) return { score: round4(ratio), status: "yellow", category: "declining" };
  return { score: round4(ratio), status: "red", category: "withdrawal" };
}

// ──────────────────────────────────────────────────────────────────────
// m15 DAP — Difficulty-Adjusted Performance (:650-686)
// NOTE: the "hard" bucket here = medium + hard.
// ──────────────────────────────────────────────────────────────────────

export function calculateDap(attempts: AttemptData[]): MetricResult {
  const easy = attempts.filter((a) => a.difficulty === "easy" && a.selectedOptionId !== null);
  const hard = attempts.filter(
    (a) => (a.difficulty === "medium" || a.difficulty === "hard") && a.selectedOptionId !== null,
  );

  if (easy.length === 0 || hard.length === 0) {
    return { score: 1.0, status: "yellow", category: "insufficient_data" };
  }

  const easyAvg = easy.reduce((s, a) => s + a.timeSpentMs, 0) / easy.length;
  const hardAvg = hard.reduce((s, a) => s + a.timeSpentMs, 0) / hard.length;

  if (easyAvg === 0) return { score: 0, status: "yellow" };

  const ratio = hardAvg / easyAvg;
  const hardAcc = hard.filter((a) => a.isCorrect).length / hard.length;

  if (ratio < 1.0) {
    if (hardAcc >= 0.7) return { score: round4(ratio), status: "yellow", category: "unusual_but_accurate" };
    return { score: round4(ratio), status: "red", category: "confused" };
  }
  if (ratio < 1.3) {
    if (hardAcc >= 0.7) return { score: round4(ratio), status: "green", category: "high_ability" };
    return { score: round4(ratio), status: "yellow", category: "flat_struggling" };
  }
  if (ratio <= 3.0) return { score: round4(ratio), status: "green", category: "appropriate" };
  if (ratio <= 5.0) return { score: round4(ratio), status: "yellow", category: "excessive" };
  return { score: round4(ratio), status: "red", category: "freezing_on_hard" };
}

// ──────────────────────────────────────────────────────────────────────
// m14 GEP — Guttman Error Pattern (:689-727)
// ──────────────────────────────────────────────────────────────────────

const GEP_DIFF_ORDER: Record<string, number> = { easy: 1, medium: 2, hard: 3, very_hard: 4 };

export function calculateGep(attempts: AttemptData[]): MetricResult {
  const attempted = answered(attempts);
  if (attempted.length < 4) {
    return { score: 1.0, status: "neutral", category: "insufficient_data" };
  }

  let guttmanErrors = 0;
  let comparisons = 0;

  for (let i = 0; i < attempted.length; i++) {
    for (let j = i + 1; j < attempted.length; j++) {
      const dI = dictGet(GEP_DIFF_ORDER, attempted[i].difficulty, 2);
      const dJ = dictGet(GEP_DIFF_ORDER, attempted[j].difficulty, 2);
      if (dI === dJ) continue;
      const [easier, harder] = dI < dJ ? [attempted[i], attempted[j]] : [attempted[j], attempted[i]];
      comparisons += 1;
      if (harder.isCorrect && !easier.isCorrect) guttmanErrors += 1;
    }
  }

  if (comparisons === 0) {
    return { score: 1.0, status: "neutral", category: "no_difficulty_pairs" };
  }

  const consistency = 1 - guttmanErrors / comparisons;

  if (consistency > 0.85) return { score: round4(consistency), status: "green", category: "consistent" };
  if (consistency >= 0.65) return { score: round4(consistency), status: "yellow", category: "mixed" };
  return { score: round4(consistency), status: "red", category: "inconsistent" };
}

// ──────────────────────────────────────────────────────────────────────
// Difficulty-weighted accuracy (:730-757)
// ──────────────────────────────────────────────────────────────────────

export const DIFFICULTY_WEIGHTS: Record<string, number> = {
  easy: 1.0,
  medium: 2.0,
  hard: 3.5,
  very_hard: 5.0,
};

export function calculateWeightedAccuracy(attempts: AttemptData[]): number {
  if (attempts.length === 0) return 0.0;
  const attempted = answered(attempts);
  if (attempted.length === 0) return 0.0;
  const wCorrect = attempted
    .filter((a) => a.isCorrect)
    .reduce((s, a) => s + dictGet(DIFFICULTY_WEIGHTS, a.difficulty, 2.0), 0);
  const wTotal = attempted.reduce((s, a) => s + dictGet(DIFFICULTY_WEIGHTS, a.difficulty, 2.0), 0);
  return wTotal > 0 ? round4(wCorrect / wTotal) : 0.0;
}

// ──────────────────────────────────────────────────────────────────────
// Student theta — minimal Elo-inspired ability estimate (:765-791)
// ──────────────────────────────────────────────────────────────────────

const DIFF_TO_THETA: Record<string, number> = { easy: -1.0, medium: 0.0, hard: 1.5, very_hard: 2.5 };

export function calculateStudentTheta(attempts: AttemptData[]): number {
  const attempted = answered(attempts);
  if (attempted.length === 0) return 0.0;

  let theta = 0.0;
  const k = 0.4; // learning rate

  for (const a of attempted) {
    const diff = dictGet(DIFF_TO_THETA, a.difficulty, 0.0);
    const expected = 1.0 / (1.0 + Math.exp(-(theta - diff)));
    const outcome = a.isCorrect ? 1.0 : 0.0;
    theta += k * (outcome - expected);
  }

  // Python: max(-3.0, min(3.0, round(theta, 3))) — round BEFORE clamp
  return Math.max(-3.0, Math.min(3.0, pythonRound(theta, 3)));
}

// ──────────────────────────────────────────────────────────────────────
// Aggregate: all 15 metrics (:798-826)
// ──────────────────────────────────────────────────────────────────────

export function calculateAllMetrics(attempts: AttemptData[], session: SessionData): AllMetrics {
  const total = answered(attempts).length;
  const correct = attempts.filter((a) => a.isCorrect).length;
  const accuracy = total > 0 ? correct / total : 0;

  return {
    // NOTE: AIR is called with questions_shown = len(attempts) — i.e. the
    // number of attempt rows (questions VIEWED), not the test's
    // total_questions (metrics_service.py:811 / ARCHITECTURE.md §9.12).
    air: calculateAir(attempts, attempts.length),
    tfa: calculateTfa(attempts, accuracy),
    ocb: calculateOcb(attempts, accuracy),
    hup: calculateHup(attempts, accuracy),
    phe: calculatePhe(attempts, accuracy),
    scc: calculateScc(session, attempts, accuracy),
    dpi: calculateDpi(attempts),
    rgd: calculateRgd(attempts),
    fad: calculateFad(attempts),
    tcr: calculateTcr(attempts),
    hsb: calculateHsb(attempts, accuracy),
    peb: calculatePeb(attempts),
    ewp: calculateEwp(attempts),
    gep: calculateGep(attempts),
    dap: calculateDap(attempts),
  };
}

/** Alias matching the Python name calculate_all_metrics_pure. */
export const calculateAllMetricsPure = calculateAllMetrics;
